#!/usr/bin/env python
# -*- coding: utf8 -*-
#
# Author: Gearóid Fox
# Copyright 2017 University College Dublin.

"""
Print number of sequences in a FASTA file
"""

import argparse
import sys
try: 
    from Bio import SeqIO
except ImportError:
    sys.stderr.write("\nError: requires Biopython SeqIO module "
                     "(http://biopython.org/)... exiting\n")
    sys.exit(1)

def main():
    description = "Print number of sequences in a FASTA file"
    parser = argparse.ArgumentParser(description=description)
    parser.add_argument("infile", help="path to FASTA file")
    args = parser.parse_args()
   
    count = 0
    with open(args.infile, "rU") as infile:
        records = SeqIO.parse(infile, "fasta")
        for _ in records:
            count += 1
    print count
    return 0
   
if __name__=="__main__":
    sys.exit(main())
